### ISSUE TITLE
프로필 페이지) 멘토링 질문

### ISSUE THREAD

**Issue by sykang013** [LikeLion-VJS10/TAING10#106]
**질문 내용**
https://github.com/LikeLion-VJS10/TAING10/tree/profile/suyeong
의 pages 폴더 안 profile.

DOM 조작으로 원하는대로 구현은 했는데, 제가 보기에도 하드코딩인것 같습니다.
코드를 몇 줄 줄일 수 있을 것 같습니다만 어디서부터 개선해나가야할지 모르겠습니다.
제가 놓친 부분과 힌트를 요청드리고싶습니다.

**Comment by s-ja** [comment]
HTML/CSS : 스타일링에서 pc기준 1920px, 타블렛 768px 모바일 320px 로 정해졌는데, 기존 작업의 경우 body의 width 를 100vw로 설정했었다. 이후 모바일과 타블렛은 각자의 너비로 미디어 쿼리 적용하여 비율을 해결 했는데, 그러고 보니 pc의 비율이 상당히 깨져 있는것으로 보인다. 처음 시작하면서 사이즈 및 비율을 어떻게 잡았어야 했을까요?

**Comment by oweaj** [comment]
![스크린샷 2023-02-06 오후 2 05 54](https://user-images.githubusercontent.com/101049520/216888150-aee5a389-56c8-4f05-a0c4-dd4fb2015e45.png)
ex) 아이디 부분 코드

회원가입 JS 부분에서 ID, PW, 비밀번호 확인, 이메일 input 입력하는 수 대로 큰 틀을 잡고 나서 진행하고 여차여차 했는데 마지막에 보니깐 너무 비효율적이고 재사용도 안될거같아서 범쌤 수업시간에 작은 부분 부터 함수로 만들어서 따로 빼서 적용한다는 부분이 생각났는데 이 작은 부분 나누는 기준이 감이 오지않습니다.

**Comment by sykang013** [comment]
//txt 변경 유틸함수, isactive, edit. 토글. 폼 전체의 템플릿을 만들어서 inserlast, 데이터만 왔다갔다. 인터폴레이터. 템플릿 리터럴. 페이지는 하나인데. t or f landering 쪼개는 연습을 하는게 좋다.

**Comment by sykang013** [comment]
addeventleistener와 쿼리셀렉터는 브라우저 속도를 늦추는 주범
(가능한 사용하지 말기)

**Comment by sykang013** [comment]
[멘토링 중 그냥 막 적은 내용입니다.]
-인코딩과 디코딩
-함수 쪼개기
실제로 서버에서는 인코딩 디코딩 없이 유니크 키 값에 따라 복호화 암호화 됨(해당 유저만) 그렇게 거쳐서 데이터에 반영됨
-델리게이션(너가 아이디 중복확인 하고있냐 회원가입하기 버튼하고있냐 등등 한 다음 벨리데이션-> )

**Comment by sykang013** [comment]
멘토링 답변 받았으므로 이슈 닫습니다.
