### ISSUE TITLE
멘토링 질문) 진섭

### ISSUE THREAD

**Issue by seovee** [LikeLion-VJS10/TAING10#107]
ajax통신을 이용해서 실시간 인기 프로그램 목록을 뿌리려고 하는데, 
ajax통신까지 완료했지만 더 이상 오류가 뜨지 않아 어떤점이 잘못된건지 모르겠습니다... ㅜㅜ

범쌤 06.ajax 수업을 참고하여 아래 사진까지 진행해보았습니다.

<img width="691" alt="스크린샷 2023-02-06 오후 1 43 32" src="https://user-images.githubusercontent.com/18073169/216885685-24cd0682-d1a9-4775-80c5-a04a1b76cd5c.png">
<img width="817" alt="스크린샷 2023-02-06 오후 1 43 45" src="https://user-images.githubusercontent.com/18073169/216885701-bae968a1-c3b7-48b3-b274-00931391a91b.png">
<img width="841" alt="스크린샷 2023-02-06 오후 1 44 01" src="https://user-images.githubusercontent.com/18073169/216885718-ac9b109c-f361-415f-8acc-952d50bf3725.png">
<img width="860" alt="스크린샷 2023-02-06 오후 1 44 22" src="https://user-images.githubusercontent.com/18073169/216885732-a2c82bd0-d30a-4611-85d9-22050b639086.png">

**Comment by sykang013** [comment]
멘로링 답변 받았으므로 이슈 닫습니다. @seovee
