### ISSUE TITLE
웹접근성 체크리스트 템플릿 작성

### ISSUE THREAD

**Issue by sykang013** [LikeLion-VJS10/TAING10#12]
https://www.notion.so/a1396f544e154127980c6ae5705e88d4?v=b3b9f7dcf789427b8f7695d4b7d4f6cc

- 사람인 웹접근성 체크리스트 기준으로, 어떻게 추릴지 고민
- 일요일 오전 회의때 논의 필요?

**Comment by SimYuseon** [comment]
프로젝트에서 사용되는 사항들 중 필수이면서 어려운 난이도는 제외하고 해보면 좋을 것 같은 거 위주로 정리하였습니다.

[웹접근성 체크리스트 링크]
https://docs.google.com/spreadsheets/d/1gJp2riR2c2p-w6fUo6JbLFtu6XtoZpcmu71-B7ug_pI/edit#gid=451044323
