### ISSUE TITLE
커밋 메시지 컨벤션

### ISSUE THREAD

**Issue by sykang013** [LikeLion-VJS10/TAING10#13]
![Image](https://user-images.githubusercontent.com/113448786/215269933-a4a005fc-f1c0-4c90-998d-ae6e09e6ae03.png)

**Comment by sykang013** [comment]
1/27 첫회의 때, 이정도만 논의됨

![Image](https://user-images.githubusercontent.com/113448786/215274405-998f87c0-6f6f-480b-988d-867c33a0c4f6.png)

**Comment by s-ja** [comment]
커밋 컨벤션 참고자료

(https://velog.io/@shin6403/Git-git-%EC%BB%A4%EB%B0%8B-%EC%BB%A8%EB%B2%A4%EC%85%98-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0)

(https://overcome-the-limits.tistory.com/entry/%ED%98%91%EC%97%85-%ED%98%91%EC%97%85%EC%9D%84-%EC%9C%84%ED%95%9C-%EA%B8%B0%EB%B3%B8%EC%A0%81%EC%9D%B8-git-%EC%BB%A4%EB%B0%8B%EC%BB%A8%EB%B2%A4%EC%85%98-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0)

**Comment by s-ja** [comment]
템플릿 - 타이틀 : 메지시 : 옵션(상태)
ex) Feat : ~~~기능 구현 및 탑제 : 진행중

으로 제안, 의논 필요
