### ISSUE TITLE
코딩 컨벤션

### ISSUE THREAD

**Issue by sykang013** [LikeLion-VJS10/TAING10#17]
![Image](https://user-images.githubusercontent.com/113448786/215270037-8fe21844-827e-4bef-b47b-039a7e9a462f.png)

**Comment by sykang013** [comment]
1/27 첫회의 때, '카멜 케이스를 사용한다' 정도만 논의함

**Comment by s-ja** [comment]
코딩컨벤션(https://ui.toast.com/fe-guide/ko_CODING-CONVENTION)
	
1.  들여쓰기의 사용에 있어서는 ‘tab’만을 사용하며 스페이스 혼용은 하지 않는다.
2. js문장 종료시 세미콜론(;)을 빠트리지 않는다.
3. 한 줄에는 하나의 문장만을 허용한다, 가독성을 위해 한 문장을 나누는것은 허용한다.
4. js에서의 명명규칙의 기본은 카멜케이스(변수 or 함수), (예약어를 사용하지 않는것은 기본_eslint).
5. 생성자의 경우 영문 대문자로 시작하는 카멜케이스 사용
6. 스코프에 따라 지역에만 사용되는 지역변수의 경우 ‘_’로 시작하여 구분한다.
7. URL, HTML 같은 범용적인 대문자 약어는 대문자 그대로 사용한다.
8. 전역변수는 사용불가를 원칙으로 하며 var 사용또한 원칙적으로는 금한다. 블록스코프 안에서 var사용을 금한다(let, const와 혼용하지 말것).
9. var 사용시 스코프에 대한 이해와 계산을 바탕으로 스코프 시작점(상단)에 선언, 명시한다.
10. const를 let 보다 위에 선언한다(한 눈에 보기 편함).
11. 외부 모듈과 내부 모듈을 구분하여 사용, 표기한다 (외부 모듈 호출의 경우 해당 파일 코드의 최상단에 위치시킬것.).
12. 배열과 객체의 선언에 있어 생성자보다 리터럴을 우선한다
13. 배열 복사시에는 순환문의 사용보다는 전개연산자 사용을 우선한다.
14. 배열 요소를 줄바꿈으로 구분할 경우 일관적으로 줄바꿈을 하여 구분할것.
15. 객체 프로퍼티는 개행하여 표시할것, 1개일 경우에도 개행한다.
16. 생성자 방식 함수는 허용하지 않는다(?)(실행속도_퍼포먼스 문제).
17. 함수는 사용 전에 선언해야 하며, 함수 선언문은 변수 선언문 다음에 오도록 한다.
18. 즉시 실행함수가 필요한 경우 정해진 규칙과 패턴 안에서만 사용하자(논의 필요).
19. 함수 표현식 대신 화살표 함수를 사용한다(논의 필요).
20. 변수 등을 조합해서 문자열을 생성하는 경우 템플릿 문자열을 이용한다.
21. mixin을 제외하고 명시적으로 prototype을 호출하지 않는다.
22. 한 줄짜리 블록일 경우라도 {}를 생략하지 않으며 명확히 줄 바꿈 하여 사용한다.
23. 키워드와 조건문 사이에 빈칸을 사용한다.
24. do-while문 사용 시 while문 끝에 세미콜론을 쓴다.
25. 삼중 등호 연산자인 ===, !==만 사용한다.
26. 함수 내에서 반환은 한 번만 한다.
27. return문 바로 위는 한 칸 비워 놓는다.
28. 주석은 설명하려는 구문에 맞춰 들여쓰기 한다.
29. 문장 끝에 주석을 작성할 경우, 한 줄 주석을 사용하며 공백을 추가한다.
30. 여러 줄 주석을 작성할 때는 *의 들여쓰기를 맞춘다. 주석의 첫 줄과 마지막 줄은 비워둔다.
31. 코드 블럭 주석 처리를 위해서는 한 줄 주석을 사용한다.
32. 콤마 다음에 값이 올 경우 공백이 있어야 한다.

이후 수정, 보완을 위해 참고할 예정
https://velog.io/@hyundong_kk/%EC%BD%94%EB%93%9C-%EC%BB%A8%EB%B2%A4%EC%85%98

커밋 컨벤션
(https://velog.io/@shin6403/Git-git-%EC%BB%A4%EB%B0%8B-%EC%BB%A8%EB%B2%A4%EC%85%98-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0)

(https://overcome-the-limits.tistory.com/entry/%ED%98%91%EC%97%85-%ED%98%91%EC%97%85%EC%9D%84-%EC%9C%84%ED%95%9C-%EA%B8%B0%EB%B3%B8%EC%A0%81%EC%9D%B8-git-%EC%BB%A4%EB%B0%8B%EC%BB%A8%EB%B2%A4%EC%85%98-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0)

**Comment by s-ja** [comment]
HTML 요소(DOM) 조작의 경우 $를 변수 앞에 붙여 구분한다?

**Comment by s-ja** [comment]
https://nuli.navercorp.com/data/convention/NHN_Coding_Conventions_for_Markup_Languages.pdf
