### ISSUE TITLE
swiper에 포함된 캡션(순위) 스타일링

### ISSUE THREAD

**Issue by seovee** [LikeLion-VJS10/TAING10#51]
**🔎 버그가 발생하는 페이지(파일)와 문제점**

**Taing.html의 Style.css의 실시간 순위 번호 추가 시, 번호의 위치가 다르고 일부가 잘려서 렌더링 됨.**

**📸 스크린샷**
<img width="394" alt="스크린샷 2023-02-03 오후 4 22 56" src="https://user-images.githubusercontent.com/18073169/216537541-fc128445-867d-4581-8c80-0e1942bdef8e.png">

잘린 부분을 해결하기 위해
1. 캡션을 감싼 부분의 높이값을 주고, position: absolute를 이용해 위치를 조정해주었다. 
2. 앱솔루트를 하는 순간, text-overflow: eclipse한 부분에 길이값을 잃어 감춰지지 않아 겹침이 생겼다.
3. 그부분은 width값을 100%를 부여해 부모값 figure를 상속받아 해결하였다. 

<img width="751" alt="스크린샷 2023-02-03 오후 4 14 39" src="https://user-images.githubusercontent.com/18073169/216536343-e090420e-0d47-4918-aa2b-bd2050bf1199.png">

<img width="284" alt="스크린샷 2023-02-03 오후 4 29 19" src="https://user-images.githubusercontent.com/18073169/216538770-c430b069-2a37-4bc3-991b-b8fde83d414d.png">

**Comment by sykang013** [comment]
버그 해결되셨다면 'close with comment' 로 이슈를 닫아주세용~ @seovee
