### ISSUE TITLE
git reset 사용하기

### ISSUE THREAD

**Issue by seovee** [LikeLion-VJS10/TAING10#52]
**🔎 버그가 발생하는 페이지(파일)와 문제점**
git commit을 잘못해서 돌려놓기 위해서 git reset --soft HEAD^를 사용해 보았는데,
수정 후 커밋을 했을 때, 커밋이 되지 않았다.

**문제해결**
소프트 리셋으로 하면 커밋기록이 남는 것으로 보인다.
<img width="432" alt="스크린샷 2023-02-03 오후 4 38 34" src="https://user-images.githubusercontent.com/18073169/216540656-955a2f22-296f-4243-9f24-86989204d413.png">

그래서 merge도 해보고 했지만, 역시 Hint를 잘 읽어봐야한다.
그냥 commit하면 소프트로 리셋된 커밋이랑 합쳐져서 커밋이 된다! 끝!

**Comment by sykang013** [comment]
버그 해결되셨다면 'close with comment' 로 이슈를 닫아주세용~ @seovee
